# 「第2の脳」RAGシステム Docker Compose設定

version: '3.8'

services:
  rag-second-brain:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-second-brain:latest
    container_name: rag-second-brain
    
    # ポートマッピング（MCPサーバー用）
    ports:
      - "8000:8000"
    
    # ボリュームマウント
    volumes:
      # 永続化データ
      - rag-data:/app/data
      - rag-logs:/app/logs
      # 設定ファイル（オプション）
      - ./config.yaml:/app/config/config.yaml:ro
      # ローカルドキュメント（オプション）
      - ./documents:/app/documents:ro
    
    # 環境変数
    environment:
      - RAG_CONFIG_PATH=/app/config/config.yaml
      - RAG_DATA_PATH=/app/data
      - PYTHONPATH=/app
      - RAG_LOG_LEVEL=INFO
    
    # リソース制限
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    
    # 再起動ポリシー
    restart: unless-stopped
    
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # ログ設定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # デフォルトコマンド
    command: ["cli", "--help"]

  # MCP サーバー専用サービス（オプション）
  rag-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-second-brain:latest
    container_name: rag-mcp-server
    
    ports:
      - "8001:8000"
    
    volumes:
      - rag-data:/app/data
      - rag-logs:/app/logs
      - ./config.yaml:/app/config/config.yaml:ro
    
    environment:
      - RAG_CONFIG_PATH=/app/config/config.yaml
      - RAG_DATA_PATH=/app/data
      - PYTHONPATH=/app
    
    command: ["mcp-server"]
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rag-data:
    driver: local
  rag-logs:
    driver: local

networks:
  default:
    name: rag-network